version: 2
updates:
- package-ecosystem: bundler
  directory: /
  ignore:
  - update-types: [version-update:semver-major]
    dependency-name: '*'
  schedule:
    interval: weekly
  assignees: [ParadoxV5]
