name: Test with RSpec
on:
  push:
    branches: [main]
    paths: [lib/**, spec/**]
  pull_request:
    branches: [main]
    paths: [lib/**, spec/**]
jobs:
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
    
    - name: Test with RSpec
      run: bundle exec rspec
