name: GitHub Packages
on:
  push:
    branches: [main]
    paths: [lib/**, spec/**]
jobs:
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
    
    - name: Package Gem
      run: bundle exec rspec
    
    - name: Publish to GitHub Packages
      run: bundle exec gem push --host https://rubygems.pkg.github.com/ParadoxV5 mygem.gem
      env: {GEM_HOST_API_KEY: "Bearer ${{ github.token }}"}
