name: Test with RSpec
on:
  push:
    branches: [main]
    paths: [lib/**, spec/**]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
    
    - name: Package Gem
      run: bundle exec rspec
